version: "3"
services:
    nginx:
        build:
            context: ./nginx
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ${DATA_ROOT}/nginx/logs:/logs
            - ${DATA_ROOT}/nginx/vhosts:/etc/nginx/vhosts
            - ${DATA_ROOT}/www:/www
        restart: always
    mysql:
        build:
            context: ./mysql
        # image: mysql:5.7
        ports:
            - "${MYSQL_PORT}:3306"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ${DATA_ROOT}/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    redis:
        build:
            context: ./redis
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - ${DATA_ROOT}/redis/conf:/usr/local/etc/redis
            - ${DATA_ROOT}/redis/data:/data
        restart: always
    # phpcli:
    #     build:
    #         context: ./php/cli
    #     volumes:
    #         - ${DATA_ROOT}/php/data:/data
    #     restart: always
    phpfpm:
        build:
            context: ./php
            dockerfile: ./fpm/Dockerfile
        ports:
            - "${PHPFPM_PORT}:9000"
        volumes:
            - ${DATA_ROOT}/php/data:/data
        restart: always
        depends_on:
            - mysql
            - redis
    app:
        build:
            context: ./php
            dockerfile: ./app/Dockerfile
        volumes:
            - ${DATA_ROOT}/php/data:/data
        restart: on-failure