version: "3"
services:
    nginx:
        build:
            context: ./nginx
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ${DATA_ROOT}/nginx/logs:/logs
            - ${DATA_ROOT}/nginx/vhosts:/etc/nginx/vhosts
            - ${DATA_ROOT}/www:/www
        restart: always